-- MySQL Script generated by MySQL Workbench
-- Sun Sep 17 13:14:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mayank.sharma-CareerFair
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mayank.sharma-CareerFair` ;

-- -----------------------------------------------------
-- Schema mayank.sharma-CareerFair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mayank.sharma-CareerFair` DEFAULT CHARACTER SET utf8 ;
USE `mayank.sharma-CareerFair` ;

-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`Student` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `degree_level` VARCHAR(45) NOT NULL,
  `isInternational` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`Booth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`Booth` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`Booth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NULL,
  `size` FLOAT UNSIGNED NULL DEFAULT 10 COMMENT 'in sqft',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`Company` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Booth_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Company_Booth1`
    FOREIGN KEY (`Booth_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Booth` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mayank.sharma-CareerFair`.`Company` (`name` ASC);

CREATE INDEX `fk_Company_Booth_idx` ON `mayank.sharma-CareerFair`.`Company` (`Booth_id` ASC);


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`Jobs` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`Jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` VARCHAR(45) NOT NULL,
  `allowsInternational` BIT(1) NOT NULL DEFAULT 0,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Jobs_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Job_Company_idx` ON `mayank.sharma-CareerFair`.`Jobs` (`Company_id` ASC);


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`application` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`application` (
  `Student_id` INT NOT NULL,
  `Jobs_id` INT NOT NULL,
  PRIMARY KEY (`Student_id`, `Jobs_id`),
  CONSTRAINT `fk_Student_applying`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jobs_applied`
    FOREIGN KEY (`Jobs_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Jobs_applied_idx` ON `mayank.sharma-CareerFair`.`application` (`Jobs_id` ASC);

CREATE INDEX `fk_Student_applying_idx` ON `mayank.sharma-CareerFair`.`application` (`Student_id` ASC);


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`JobAllowsDepartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`JobAllowsDepartment` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`JobAllowsDepartment` (
  `department` VARCHAR(50) NOT NULL,
  `Jobs_id` INT NOT NULL,
  CONSTRAINT `fk_Jobs2`
    FOREIGN KEY (`Jobs_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Job_allows_Department_idx` ON `mayank.sharma-CareerFair`.`JobAllowsDepartment` (`Jobs_id` ASC);


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`JobAllowsDegreeLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`JobAllowsDegreeLevel` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`JobAllowsDegreeLevel` (
  `degree` VARCHAR(50) NOT NULL,
  `Jobs_id` INT NOT NULL,
  CONSTRAINT `fk_Jobs1`
    FOREIGN KEY (`Jobs_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Job_allows_Degree_idx` ON `mayank.sharma-CareerFair`.`JobAllowsDegreeLevel` (`Jobs_id` ASC);


-- -----------------------------------------------------
-- Table `mayank.sharma-CareerFair`.`Sponsorship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mayank.sharma-CareerFair`.`Sponsorship` ;

CREATE TABLE IF NOT EXISTS `mayank.sharma-CareerFair`.`Sponsorship` (
  `amount` FLOAT NOT NULL COMMENT 'in USD',
  `category` INT(10) GENERATED ALWAYS AS (amount / 5000) VIRTUAL,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`Company_id`),
  CONSTRAINT `fk_Sponsorship_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `mayank.sharma-CareerFair`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
